- src/UNL/Peoplefinder.php
It appears that HR is changing the format of their addresses.  This will first check for the new format and then attempt to parse the old format.
> Use `<building code> <room number>` for pasing building codes

- www/scripts/peoplefinder.js
Without encoding, the URL was being set to something like `#q/Michael Fairchild`, which is invalid.  Encoding produces something like `#/Michael%20Fairchild`.
This was causing issues with UNLchat emails not routing correctly.
> Encode hash values for URLs

- examples/facultyDataTest.php
- src/UNL/Knowledge/Driver/REST.php
- www/config-sample.inc.php
- www/templates/html/Knowledge.tpl.php
Used memcached to cache results for the API for one week. Should be easy
to set up and add into PHP. Be sure to copy over the settings from
config.sample.php into the config.inc.php file and make the appropriate
changes if necessary.
> Add caching functionality to Digital Measures API

- src/UNL/Officefinder/Department.php
Move the default assignment of `false` to before permission check logic. The permission check logic will only change the value to `true` if they have permission. This was always returning false.
@kabel I *think* this works, but I am unable to test locally due to pear issue. Can you verify that it fixes the issue?
> Restore editor permissions

- .travis.yml
- src/UNL/Peoplefinder/Driver/LDAP.php
- src/UNL/Peoplefinder/SearchController.php
Some LDAP queries, especially those with 3 character searches could take quite some time. This will cache all LDAP queries for a default of 8 hours, as well as prevent cache stampedes by returning an empty result set until the original query finishes.
> cache LDAP queries

- src/UNL/Peoplefinder/Driver/LDAP/StandardFilter.php
Searches with extra spaces like `michael ` or `michael   fairchild` were causing invalid filters to be created.
> Remove empty parts of a query

- src/UNL/Peoplefinder/Record/Avatar.php
I find this a little difficult to explain, but I will try anyway. The DNS record for planetred might not be the same in directory.unl.edu and gravatar. Because DNS can take some time to propagate, directory will get the new ip address before gravatar. By sending the effective URL to gravatar, there is a potential that the URL might not exist because gravatar is still referring to the old server. By sending the `$profileIconUrl` to gravatar, the request is bound to work regardless of gravatar's dns cache.
The same goes with clients. Client computers might not have the same DNS record as directory.unl.edu and therefor URLs might not resolve correctly.
> Return the original profile icon URL which should always work

- src/UNL/Peoplefinder/Record/Avatar.php
Reverts unl/UNL_Directory#42
Hold until DNS problems go away.
> Revert "Return the original profile icon URL which should always work"

- src/UNL/Officefinder/DepartmentList/NameSearch.php
Official (org_unit) departments should always be considered in searches,
even when they do not have any child yellow pages. The inner join was
excluding such possibilty.
> Fix bug in department search - excluding orgs w/o yellow pages

- src/UNL/Peoplefinder/Record.php
The query is already bing cached at the driver level for a default of 8 hours, while this was caching results for a day. This could lead to not only duplicate caches but also confusion as to how long it will take for the record to leave the cache.
This probably fixes some issues related #51 but there still might be others.
> Remove conflicting caches

- scripts/flag_sap_orgs_without_employees.php
- src/UNL/Officefinder/DepartmentList/OfficialOrgUnitsNoChildren.php
- src/UNL/Peoplefinder/Department.php
Reuses a singleton `UNL_Peoplefinder` instance when fetching employees via HR number. Also uses faster query for selecting departments without child listings.
> Fix script that suppresses official units w/o children and employees

- examples/cache_example.txt
- scripts/cache_knowledge.php
- src/UNL/Knowledge/Driver/REST.php
Queries to Digital Measures were causing epic server load,
especially on digital signage where offices/departments
were being printed. Instead of getting this data on demand,
this commit adds a script which will be added to cron to
grab the data every 15 minutes from Digital Measures, and
cache it for fast retrieval on all queries.
This method can be tested by following the directions given
in examples/cache_example.txt .
> Add methods and script to cache all Faculty CV data

- www/js/directory.js
If a query is only one word and nothing is found, the progress bar will just continue trucking. This fixes that and shows the error message when nothing could be found.
> Show that a one word search failed

- www/less/directory.less
- www/templates/html/Officefinder/Department/Summary.tpl.php
- www/templates/html/Peoplefinder/Help.tpl.php
- www/templates/html/Peoplefinder/Record.tpl.php
The link icon was confusing, removed from use.
The link color will be red in result lists and the grey color on the
result's single page. This is consistent with styles from events.
> Remove the link icon and color override in result headlines

- src/UNL/Peoplefinder/Record.php
a recent update to LDAP now always give eduPersonNickname the same value as CN. This adjusts logic to account for that circumstance.
> Fix the display of names

- src/UNL/Peoplefinder.php
These are the result of recent LDAP changes, and are preventing some people from being displayed.
> whitelist new affiliations

- src/UNL/Peoplefinder/Record.php
Zip codes are now being provided by LDAP without a dash after the first 5 digits. This different was preventing the regex from matching and thus the zip code from displaying.
> Fix the display of zip codes

- src/UNL/Peoplefinder.php
- src/UNL/Peoplefinder/Driver/LDAP/Entry.php
- src/UNL/Peoplefinder/Record.php
Logic was just being applied to some endpoints and representations. This corrects several of the issues in the LDAP record itself before it is used anywhere else. For example, JSON endpoints should now match the expected values.
> 	Apply fixes to all data endpoints

- www/js/directory.js
In some cases, the modal would load with an error because it tried to load based on the target element. That is fine as long as the target element is the `<a href>`, but that isn't the case here. So when the container is clicked, grab the closest `a` element.
> fix the qr code link

- www/templates/html/Peoplefinder/StandardForm.tpl.php
It is already in the footer and isn't used that often anyway.
> remove the help link by the search bar

- src/UNL/Peoplefinder.php
Currently the code makes many calls to Oracle, and if the database
is not found, the timeout on each of these is pretty long. I couldn't
find a good way to turn this down in the codebase. So, for the
All Campus outage this Sunday, I'm implementing this change which will
allow me to turn off this connection temporarily.
Closes #93
> Allow Oracle connection to be turned off

- src/UNL/Peoplefinder/Record.php
- tests/PeoplefinderRecordTest.php
- www/templates/html/Peoplefinder/Record.tpl.php
This converts the way that the building is identified in the address from
```
[unlBuildingCode] [number]
```
to
```
[unlBuildingName] ([unlBuildingCode]) [number]
```
It also adds logic to always converts the building code string to uppercase when comparing to building lists (which expects all caps).
> Display the full building name

- src/UNL/Peoplefinder/Driver/OracleDB.php
- src/UNL/Peoplefinder/Record.php
- www/templates/html/Peoplefinder/Record.tpl.php
* updates queries to reference a database view that contains central appointments
* people with central appointments will not have a primary HR department defined in AD, so adjust logic to account for that
* The appointments will not be displayed until the new ITS org units are manually entered into the officefinder database
> Allow the display of central appointments

- www/js/directory.js
Just disabling for now. Will likely remove completely.  Currently causes intended sticky div to overlay scrolled content.
> Disable jquery sticky kit plugin sice not behaving correctly in 5.0 template implementation

- .gitignore
- README.md
- data/test-data.inc.php
- data/test-data.inc_sample.php
- src/UNL/Peoplefinder.php
- src/UNL/Peoplefinder/Driver/LDAP.php
- src/UNL/Peoplefinder/Driver/OracleDB.php
- www/config-sample.inc.php
Closes #143 
The idea is to simulate a person record that doesn't exist in the official identity system.
Reasons to do this:
- So there is a permanent user (that won't quit or retire or be removed by IAM) for another system to use for testing. See https://github.com/unlcms/unl_user/pull/3
- As a test record for possible schema changes or to see how different data affects output.
- As an Easter egg. Right now we prompt people on the homepage to search for "Herbie Husker" but that doesn't return a result.
It is coded to be able to be enabled/disabled and customized per environment.  My plan is to deploy as-is with an exposed "hhusker1" sample person.
Deployed to test:
https://directory-test.unl - edu/#q/Herbie%20Husker
https://directory-test.unl - edu/people/hhusker1
> Add a test user

- scripts/cache_department_personnel.php
- src/UNL/Peoplefinder.php
- src/UNL/Peoplefinder/Cache.php
- src/UNL/Peoplefinder/Department/PersonnelSubtree.php
- src/UNL/Peoplefinder/Driver/LDAP.php
- src/UNL/Peoplefinder/Driver/OracleDB.php
Added logic to allow page to rendered without cached data and to reset the cache items for the page with the new data by adding `reset-cache` to the query string of the page. Cache items include LDAP and Oracle queries involved in the collecting the data of the page.
Example: https://directory-test.unl.edu/departments/50000955/personnelsubtree?format=xml&reset-cache
Also added a script to prime the departments used for digital signage. This script could be run daily to prime the cache for those departments, but I'll suggest that Nate M. uses the query string instead and only pull the data once a day.
> Implement cache prime for department personnel tree

- src/UNL/Peoplefinder.php
- src/UNL/Peoplefinder/Driver/LDAP.php
- src/UNL/Peoplefinder/Driver/LDAP/AdvancedFilter.php
- src/UNL/Peoplefinder/Driver/LDAP/AffiliationFilter.php
- src/UNL/Peoplefinder/Driver/LDAP/Entry.php
- src/UNL/Peoplefinder/Driver/LDAP/TelephoneFilter.php
- src/UNL/Peoplefinder/Driver/OracleDB.php
- src/UNL/Peoplefinder/Person/Roles.php
- src/UNL/Peoplefinder/Record.php
- www/templates/html/Peoplefinder/Person/Roles.tpl.php
- www/templates/vcard/Peoplefinder/Record.tpl.php
Note: This PR branch has been applied to both the Production (https://directory.unl.edu) and Test (https://directory-test.unl.edu) sites for testing.
Changes made:
* Add affiliation constants
* Prevent person records with only Retiree and Volunteer affiliations.
* Prevent display of roles of Retirees Org Unit or with title/description of 'retiree'
I'm not sure if these changes will prevent all retirees or retiree information from displaying or if some valid person may be excluded, but it should handle most cases.
> Updates to prevent retirees from displaying in directory

- src/UNL/Peoplefinder/Driver/OracleDB.php
Improved speed by breaking up the fixLDAP query into two smaller queries. Everything going to the slow affiliations view is just a normal select.
> Changed big query to fixLDAP into two smaller queries

- src/UNL/Peoplefinder/Driver/OracleDB.php
- www/config-sample.inc.php
We were having issues with some people having multiple emails in the oracle db. It would choose to display the last email. 
Added a priority list in the config.inc.php and only have emails swap out if they are more preferred.
> Email Swap Priority

- src/UNL/Peoplefinder/Record/Avatar.php
`format=JPEG` when added to the avatar URL would cause the image to not be pulled up properly
> fix case sensitive file extension
