src/UNL/Peoplefinder/Driver/LDAP.php
Not sure if this actually does anything, but it closes #11
=> Sort the LDAP results for fetching roles by unlListingOrder

src/UNL/Peoplefinder/Person.php, www/templates/html/Peoplefinder/Person.tpl.php
This fixes issues with services that do not expect the knowledge HTML in hcard requests. This fix is back-ported from the design-refresh branch.
=> Only render person hcard when hcard format is requsted

www/index.php
The vcard format should trigger a download for the UNL_Peoplefinder_Person object too.
Back-ported from new-design branch.
=> Restore vcard download for Person object

composer.json, composer.lock, src/UNL/Knowledge/Records.php, src/UNL/Peoplefinder/Record.php, src/UNL/Peoplefinder/Savvy.php, www/templates/html/Knowledge/Records.tpl.php, www/templates/xml/Peoplefinder/Record.tpl.php
Refactors rendering logic for the Knowledge records to allow them to be injected into the person record more easily.
=> Add Faculty CV Data to API endpoints

src/UNL/Peoplefinder/Driver/LDAP.php
10 is rather excessive. I hesitate to lower it even further at the moment.
=> Reduce retries to 5

src/UNL/Peoplefinder/Record/Avatar.php
@kabel Please test this and make sure it works as you expect it to.
=> Support the new version of planetred and make it backwards compatible

composer.json, composer.lock, src/UNL/Officefinder.php, src/UNL/Officefinder/Auth.php, src/UNL/Peoplefinder/Cache.php, src/UNL/Peoplefinder/Record/Avatar.php
Replaces HTTP_Request2 with GuzzleHttp and SimpleCAS with phpCAS.
=> Remove the pear repository dependency

src/UNL/Officefinder/DepartmentList/NameSearch.php
=> Exclude suppressed departments from name search

src/UNL/Knowledge/Driver/REST.php
this change is live, this PR is purely fore review.
=> add a timeout for when digital measures is slow/down

www/js/directory.js
Fix ampersands not being decoded
closes #57
=> Prevent the internet from blowing up

src/UNL/Peoplefinder.php, www/js/directory.js, www/less/directory.less, www/templates/html/CorrectionForm.tpl.php, www/templates/html/Officefinder/Department.tpl.php, www/templates/html/Officefinder/Department/Summary.tpl.php, www/templates/html/Peoplefinder.tpl.php, www/templates/html/Peoplefinder/Record.tpl.php, www/templates/html/static/after-main.tpl.php, www/templates/html/static/correctionButtonTemplate.tpl.php, www/templates/html/static/jsrender/Correction/ButtonTemplate.tpl.php, www/templates/html/static/modal.tpl.php
The corrections form somehow got lost, I found it.
=> Add a corrections form

src/UNL/Peoplefinder/Record/Avatar.php
This should help reduce server load
=> Cache the default profile URLs for a short time

www/less/directory.less
This is a temporary fix until the issue is fixed in the next version of the framework
=> Improve mobile nav

www/less/directory.less, www/templates/html/Knowledge/Records.tpl.php
- Update markup to improve icon accessibility
- Improve layout and alignment of icon, heading, and content
**Before**
**After**
=> Knowledge section markup, layout improvements

.travis.yml, composer.json, composer.lock, src/UNL/Officefinder/Department.php, www/templates/json/Officefinder/Department.tpl.php
Add as much detail as we know, and include unofficial departments. This is to support CMS integration.
=> Add more details to json output

www/js/directory.js
The selector changed when the link was converted to a button, and the now that it is a button, we should trigger the print when mainstate=1
fixes #85
=> Fix the print button

.gitignore, www/less/directory.less, www/templates/html/CorrectionForm.tpl.php, www/templates/html/Officefinder/DepartmentList/AcademicDepartments.tpl.php, www/templates/html/Peoplefinder/FacultyEducationList.tpl.php, www/templates/html/Peoplefinder/Help.tpl.php, www/templates/html/Peoplefinder/Instructions.tpl.php, www/templates/html/Peoplefinder/StandardForm.tpl.php, www/templates/html/static/contact-info.tpl.php, www/templates/html/static/head.tpl.php
=> Front end adjustments

www/templates/html/Officefinder/DepartmentList/AlphaListing.tpl.php, www/templates/html/Officefinder/DepartmentList/AlphaListing/LoginRequired.tpl.php, www/templates/html/Peoplefinder.tpl.php, www/templates/html/Peoplefinder/Record/CampusNumber.tpl.php, www/templates/html/Peoplefinder/Record/TelephoneNumber.tpl.php
=> Print style improvements for the paper document

src/UNL/Peoplefinder/Driver/OracleDB.php
=> Add Title Modifiers to role output

src/UNL/Peoplefinder/Driver/OracleDB.php, src/UNL/Peoplefinder/Record.php
Make sure that staff/faculty who are also students with a privacy flag set are not shown as students
=> Remove the student affiliation if the privacy flag is set

www/templates/html/Peoplefinder/Record.tpl.php
Fixes display bug with professor pages with knowledge grid:
https://directory.unl.edu/people/sgardner2
=> Fix knowledge grid issue

src/UNL/Peoplefinder/Driver/OracleDB.php
You may test at https://directory-test.unl.edu/
=> Add order by appointments.directory_order ASC to peoplefinder roles results

Gruntfile.js, www/less/directory-print.less, www/less/directory.less, www/templates/html/Officefinder/Department/Summary.tpl.php, www/templates/html/Peoplefinder/Record.tpl.php, www/templates/html/static/head.tpl.php, www/templates/html/static/jsrender/Correction/ButtonTemplate.tpl.php
Update print styles and separate CSS into its own stylesheet.
=> Update print CSS

package-lock.json, www/templates/html/Peoplefinder/Instructions.tpl.php
- Update layout of instructions cards
- Update Node modules
- Update code style: 
- Convert indents to four spaces
- Remove ` /` from self-closing tags
- Add periods to end of `alt` text
=> Update home page design

www/templates/html/Peoplefinder/Record.tpl.php
Test: https://directory-test.unl.edu/#q/roberts
Of the three faculty in `roberts` results, Sarah Roberts has activity insight information.
=> Display knowledge info on HCard display

www/templates/html/Officefinder/Department/Summary.tpl.php
To address https://projects.unl.edu/projects/7921?modal=Task-73558-7921
Can test at https://directory-test.unl.edu
=> Add view department link on department summary

src/UNL/Peoplefinder/Driver/LDAP.php
Can test on https://directory-test.unl.edu
Some Test Examples
https://directory-test.unl.edu/people/jsturek8.json
https://directory-test.unl.edu/people/jsturek8
https://directory-test.unl.edu/people/tstrickman2.json
https://directory-test.unl.edu/people/tstrickman2
https://directory-test.unl.edu/people/fsolich2.json
https://directory-test.unl.edu/people/fsolich2
=> Limit LDAP to displayable affiliations

www/templates/html/Officefinder/Department/Summary.tpl.php
DCF class applied to id attribute instead of class attribute.
=> Correction Form Bug Fix

www/templates/html/Officefinder/TreeView.tpl.php
https://directory.unl.edu/departments/tree
=> Dark mode issue on tree

src/UNL/Peoplefinder/Record.php, www/templates/html/Peoplefinder.tpl.php
Such as /people/01234567 instead of /people/hhusker1
=> Support accessing a people record with NUID 

composer.json, composer.lock, www/templates/html/Peoplefinder.tpl.php
Do not commit until WDN version 5.3 is available.
=> WIP: Support WDN Version 5.3

www/templates/html/Exception.tpl.php, www/templates/html/Peoplefinder/SearchController.tpl.php, www/templates/html/static/jsrender/Search/NoticeTemplate.tpl.php
Test branch on https://directory-test.unl.edu/
=> Implement DCF Notice

www/templates/html/PaginationLinks.tpl.php, www/templates/html/Peoplefinder/FacultyEducationList.tpl.php
These changes are dependent on WDN rollout with support for DCF pagination.
=> Implement DCF Pagination

www/templates/html/static/contact-info.tpl.php
changed footer text to match web audit. 
This
This application is a product of the [Digital Experience Group at Nebraska](https://dxg.unl.edu/). DXG is a partnership of [University Communication](https://ucomm.unl.edu/) and [Information Technology Services](https://its.unl.edu/).
to
This application is a product of the [Digital Experience Group](https://dxg.unl.edu/) at [Nebraska](https://www.unl.edu/). DXG is part of [University Communication & Marketing](https://ucomm.unl.edu/).
=> changed footer text to match web audit

src/UNL/Peoplefinder/Record.php, src/UNL/Peoplefinder/Record/Avatar.php
This is for the next-gen CMS blurry image issue
[https://github.com/unlcms/project-herbie/issues/458](https://github.com/unlcms/project-herbie/issues/458)
=> Added original size for directory images and made default original

src/UNL/Peoplefinder/Record.php, src/UNL/Peoplefinder/Record/Avatar.php
Original sized avatars are un-cropped, swapped it from original to medium
=> Updated Default Avatar

src/UNL/Peoplefinder.php, www/config-sample.inc.php, www/templates/json/Peoplefinder/Record.tpl.php, www/templates/php/Peoplefinder/Record.tpl.php, www/templates/xml/Peoplefinder/Record.tpl.php
Only allow NUID to be seen by specific IP addresses
=> Roll back nuid

src/UNL/Peoplefinder/Record.php, src/UNL/PersonInfo.php, www/templates/html/Peoplefinder/Record.tpl.php
Fix issues outside of directory that were using the old formats of vcard and json
=> Fix issues related to vcard and json

www/templates/html/PersonInfo/Instructions.tpl.php
Some people have asked what the recommended size of the image was so I added some help text to help with that
=> added more help text about avatar image size

src/UNL/APIController.php, www/index.php, www/sample.htaccess
Changes:
- Added API route `/api/v1/emailToUID` to convert a person's email to their UID
=> Added API route for converting user's email to UID

composer.json, composer.lock, www/templates/html/Peoplefinder.tpl.php
Fix issues where js would not load correctly and re-added swift mailer
=> Fix minor issues with the department pages
